// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Input$ReactHooksTemplate = require("./Input.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Input$ReactHooksTemplate.make, {
          label: "Choose your URL : "
        }), "root");

/*  Not a pure module */
