// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var GeneratorForm$DvbGenerator = require("./GeneratorForm.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(GeneratorForm$DvbGenerator.make, { }), "root");

/*  Not a pure module */
