// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Input(Props) {
  var label = Props.label;
  return React.createElement("label", {
              htmlFor: "url"
            }, label, React.createElement("input", {
                  id: "url",
                  type: "text"
                }));
}

var make = Input;

exports.make = make;
/* react Not a pure module */
