// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Emotion = require("bs-emotion/src/Emotion.bs.js");

var inputStyle = Emotion.css(undefined, /* :: */[
      Emotion.label("inputStyle"),
      /* :: */[
        Emotion.borderRadius(/* `px */[
              25096,
              2
            ]),
        /* :: */[
          Emotion.backgroundColor(/* `hex */[
                5194459,
                "f2efea"
              ]),
          /* :: */[
            Emotion.borderWidth(/* `px */[
                  25096,
                  0
                ]),
            /* :: */[
              Emotion.fontSize(/* `px */[
                    25096,
                    20
                  ]),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var labelStyle = Emotion.css(undefined, /* :: */[
      Emotion.label("labelStyle"),
      /* :: */[
        Emotion.color(/* `hex */[
              5194459,
              "dbd56e"
            ]),
        /* :: */[
          Emotion.fontSize(/* `px */[
                25096,
                20
              ]),
          /* [] */0
        ]
      ]
    ]);

function Input(Props) {
  var label = Props.label;
  return React.createElement("label", {
              className: labelStyle,
              htmlFor: "url"
            }, label, React.createElement("br", undefined), React.createElement("input", {
                  className: inputStyle,
                  id: "url",
                  type: "text"
                }));
}

var make = Input;

exports.inputStyle = inputStyle;
exports.labelStyle = labelStyle;
exports.make = make;
/* inputStyle Not a pure module */
